// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqwstixdmwkydcxxkvlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxd3N0aXhkbXdreWRjeHhrdmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTczODYsImV4cCI6MjA3MzUzMzM4Nn0.Mg1SAwtPuZ1Su9fJFkx118vd1vCzJq8d7jruLB1xYCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});